#!/usr/bin/env bash

# Examples:
#     clbin hello.txt              # paste file (name/ext will be set).
#     echo Hello world. | clbin    # read from STDIN (won't set name/ext).
#     clbin -n 1 self_destruct.txt # paste will be deleted after one read.
#     clbin -i ID hello.txt        # replace ID, if you have permisscomn.
#     clbin -d ID

clbin() {
    local opts
    local OPTIND
    [ -f "$HOME/.netrc" ] && opts='-n'
    while getopts ":hd:i:n:" x; do
        case $x in
            h) echo "clbin [-d ID] [-i ID] [-n N] [opts]"; return;;
            d) $echo curl $opts -X DELETE clbin.com/$OPTARG; return;;
            i) opts="$opts -X PUT"; local id="$OPTARG";;
            n) opts="$opts -F read:1=$OPTARG";;
        esac
    done
    shift $(($OPTIND - 1))
    [ -t 0 ] && {
        local filename="$1"
        shift
        [ "$filename" ] && {
            curl $opts -F f:1=@"$filename" $* clbin.com/$id
            return
        }
        echo "^C to cancel, ^D to send."
    }
    curl $opts -F 'clbin<-' $* https://clbin.com
    curl -F 'clbin=<-' https://clbin.com
}

clbin $*
